image:
- Visual Studio 2015
- Visual Studio 2017

version: "{branch}-{build}"

build_script:
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017"){.\scripts\nuget_build.ps1}

test_script:
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015"){.\tests\autotest-appveyor.ps1}

artifacts:
  - path: .\scripts\*.nupkg